import { expect, test } from '@playwright/test'
import catalogue from '../public/data/ports.json' with { type: 'json' }

for (const viewport of [{ width: 390, height: 844 }, { width: 1920, height: 1080 }]) {
  test(`search and hero cards work at ${viewport.width}px`, async ({ page }) => {
    await page.setViewportSize(viewport)
    await page.goto('/')
    const search = page.getByRole('combobox', { name: 'Find a port' })
    await expect(search).toBeVisible()
    await search.click()
    await expect(page.getByRole('listbox', { name: 'Matching ports' }).getByRole('option')).toHaveCount(catalogue.length)
    await search.fill('Shenzhen')
    await search.press('ArrowDown')
    await expect(search).toHaveAttribute('aria-activedescendant', 'port-result-yantian')
    await search.press('Enter')
    await expect(search).toBeFocused()
    await expect(search).toHaveAttribute('aria-expanded', 'false')
    const card = page.getByRole('article', { name: 'Yantian port details' })
    await expect(card.getByRole('heading')).toHaveText('Yantian')
    await expect(card).toContainText('33.40')
    await expect(card).toContainText('#4')
    await expect(card).toContainText('2024')
    await expect(card).toContainText('Shenzhen port system')
    await expect(card.getByRole('link', { name: 'World Shipping Council' })).toHaveAttribute('href', 'https://www.worldshipping.org/top-50-container-ports')
    await expect(page.locator('[data-port-id="yantian"][data-selected=true] text')).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(viewport.width)
    await page.getByRole('button', { name: 'Close port details' }).click()
    await expect(card).toHaveCount(0)
    await expect(search).toBeFocused()
    await expect(search).toHaveValue('')
    await search.fill('Cai Mep')
    await page.getByRole('listbox', { name: 'Matching ports' }).getByRole('option').click()
    await expect(page.getByRole('article', { name: 'Cai Mep port details' })).toContainText('CMIT')
    await search.fill('no such port')
    await expect(page.getByRole('status')).toHaveText('No matching ports. Try another name.')
    await search.press('Escape')
    await expect(search).toHaveAttribute('aria-expanded', 'false')
    await page.getByRole('button', { name: 'Clear port search and selection' }).click()
    await expect(page.getByRole('article')).toHaveCount(0)
    await expect(search).toHaveValue('')
  })
}

test('keyboard navigation, published tonnage and missing statistics remain distinct', async ({ page }) => {
  await page.goto('/')
  const search = page.getByRole('combobox', { name: 'Find a port' })
  await search.fill('Port Hedland')
  await search.press('ArrowUp')
  await search.press('Enter')
  const card = page.getByRole('article', { name: 'Port Hedland port details' })
  await expect(card).toContainText('580.4')
  await expect(card).toContainText('million tonnes')
  await expect(card).toContainText('FY 2025–26')
  await expect(card).not.toContainText('Vessel arrivals')
  await page.getByRole('button', { name: 'Cargo', exact: true }).click()
  await page.getByRole('button', { name: 'Tankers', exact: true }).click()
  await page.locator('#time').fill('1200000')
  await expect(card).toContainText('580.4')
  await search.fill('Palermo')
  await search.press('Enter')
  const empty = page.getByRole('article', { name: 'Palermo port details' })
  await expect(empty).toContainText('haven’t been added')
  await expect(empty.locator('.port-metrics')).toHaveCount(0)
})

test('map labels open port cards and region changes clear the selected port', async ({ page }) => {
  await page.setViewportSize({ width: 1920, height: 1080 })
  await page.goto('/')
  const label = page.locator('[data-port-id="los-angeles"] rect')
  await expect(label).toBeVisible()
  const box = await label.boundingBox()
  await page.mouse.click(box!.x + box!.width / 2, box!.y + box!.height / 2)
  await expect(page.getByRole('article', { name: 'Los Angeles port details' })).toContainText('1,807')
  await expect(page.getByRole('article')).toContainText('Vessel arrivals · all types')
  await page.getByRole('button', { name: '01China', exact: true }).click()
  await expect(page.getByRole('article')).toHaveCount(0)
  await expect(page.getByRole('combobox', { name: 'Find a port' })).toHaveValue('')
})

test('port cards preserve the playback controls on a small desktop', async ({ page }) => {
  await page.setViewportSize({ width: 1366, height: 768 })
  await page.goto('/')
  const search = page.getByRole('combobox', { name: 'Find a port' })
  for (const name of ['Los Angeles', 'Guangxi', 'Port Hedland']) {
    await search.fill(name)
    await search.press('Enter')
    await expect(page.getByRole('article')).toBeVisible()
    const footer = await page.locator('.playback').boundingBox()
    expect(footer!.y + footer!.height).toBeLessThanOrEqual(769)
    const card = await page.getByRole('article').boundingBox()
    expect(card!.x + card!.width).toBeLessThanOrEqual(1366)
  }
})
